ipam:
    subnets:
        - used: false
          cidr: 10.20.0.0/24
        - used: false
          cidr: 10.20.1.0/24
        - used: false
          cidr: 10.20.2.0/24
        - used: false
          cidr: 10.20.3.0/24
        - used: false
          cidr: 10.20.4.0/24
        - used: false
          cidr: 10.20.5.0/24
        - used: false
          cidr: 10.20.6.0/24
        - used: false
          cidr: 10.20.7.0/24
        - used: false
          cidr: 10.20.8.0/24
        - used: false
          cidr: 10.20.9.0/24
        - used: false
          cidr: 10.20.10.0/24
        - used: false
          cidr: 10.20.11.0/24
        - used: false
          cidr: 10.20.12.0/24
        - used: false
          cidr: 10.20.13.0/24
        - used: false
          cidr: 10.20.14.0/24
        - used: false
          cidr: 10.20.15.0/24
        - used: false
          cidr: 10.20.16.0/24
        - used: false
          cidr: 10.20.17.0/24
        - used: false
          cidr: 10.20.18.0/24
        - used: false
          cidr: 10.20.19.0/24
        - used: false
          cidr: 10.20.20.0/24
        - used: false
          cidr: 10.20.21.0/24
        - used: false
          cidr: 10.20.22.0/24
        - used: false
          cidr: 10.20.23.0/24
        - used: false
          cidr: 10.20.24.0/24
        - used: false
          cidr: 10.20.25.0/24
        - used: false
          cidr: 10.20.26.0/24
        - used: false
          cidr: 10.20.27.0/24
        - used: false
          cidr: 10.20.28.0/24
        - used: false
          cidr: 10.20.29.0/24
        - used: false
          cidr: 10.20.30.0/24
        - used: false
          cidr: 10.20.31.0/24
        - used: false
          cidr: 10.20.32.0/24
        - used: false
          cidr: 10.20.33.0/24
        - used: false
          cidr: 10.20.34.0/24
        - used: false
          cidr: 10.20.35.0/24
        - used: false
          cidr: 10.20.36.0/24
        - used: false
          cidr: 10.20.37.0/24
        - used: false
          cidr: 10.20.38.0/24
        - used: false
          cidr: 10.20.39.0/24
        - used: false
          cidr: 10.20.40.0/24
        - used: false
          cidr: 10.20.41.0/24
        - used: false
          cidr: 10.20.42.0/24
        - used: false
          cidr: 10.20.43.0/24
        - used: false
          cidr: 10.20.44.0/24
        - used: false
          cidr: 10.20.45.0/24
        - used: false
          cidr: 10.20.46.0/24
        - used: false
          cidr: 10.20.47.0/24
        - used: false
          cidr: 10.20.48.0/24
        - used: false
          cidr: 10.20.49.0/24
        - used: false
          cidr: 10.20.50.0/24
        - used: false
          cidr: 10.20.51.0/24
        - used: false
          cidr: 10.20.52.0/24
        - used: false
          cidr: 10.20.53.0/24
        - used: false
          cidr: 10.20.54.0/24
        - used: false
          cidr: 10.20.55.0/24
        - used: false
          cidr: 10.20.56.0/24
        - used: false
          cidr: 10.20.57.0/24
        - used: false
          cidr: 10.20.58.0/24
        - used: false
          cidr: 10.20.59.0/24
        - used: false
          cidr: 10.20.60.0/24
        - used: false
          cidr: 10.20.61.0/24
        - used: false
          cidr: 10.20.62.0/24
        - used: false
          cidr: 10.20.63.0/24
        - used: false
          cidr: 10.20.64.0/24
        - used: false
          cidr: 10.20.65.0/24
        - used: false
          cidr: 10.20.66.0/24
        - used: false
          cidr: 10.20.67.0/24
        - used: false
          cidr: 10.20.68.0/24
        - used: false
          cidr: 10.20.69.0/24
        - used: false
          cidr: 10.20.70.0/24
        - used: false
          cidr: 10.20.71.0/24
        - used: false
          cidr: 10.20.72.0/24
        - used: false
          cidr: 10.20.73.0/24
        - used: false
          cidr: 10.20.74.0/24
        - used: false
          cidr: 10.20.75.0/24
        - used: false
          cidr: 10.20.76.0/24
        - used: false
          cidr: 10.20.77.0/24
        - used: false
          cidr: 10.20.78.0/24
        - used: false
          cidr: 10.20.79.0/24
        - used: false
          cidr: 10.20.80.0/24
        - used: false
          cidr: 10.20.81.0/24
        - used: false
          cidr: 10.20.82.0/24
        - used: false
          cidr: 10.20.83.0/24
        - used: false
          cidr: 10.20.84.0/24
        - used: false
          cidr: 10.20.85.0/24
        - used: false
          cidr: 10.20.86.0/24
        - used: false
          cidr: 10.20.87.0/24
        - used: false
          cidr: 10.20.88.0/24
        - used: false
          cidr: 10.20.89.0/24
        - used: false
          cidr: 10.20.90.0/24
        - used: false
          cidr: 10.20.91.0/24
        - used: false
          cidr: 10.20.92.0/24
        - used: false
          cidr: 10.20.93.0/24
        - used: false
          cidr: 10.20.94.0/24
        - used: false
          cidr: 10.20.95.0/24
        - used: false
          cidr: 10.20.96.0/24
        - used: false
          cidr: 10.20.97.0/24
        - used: false
          cidr: 10.20.98.0/24
        - used: false
          cidr: 10.20.99.0/24
        - used: false
          cidr: 10.20.100.0/24
        - used: false
          cidr: 10.20.101.0/24
        - used: false
          cidr: 10.20.102.0/24
        - used: false
          cidr: 10.20.103.0/24
        - used: false
          cidr: 10.20.104.0/24
        - used: false
          cidr: 10.20.105.0/24
        - used: false
          cidr: 10.20.106.0/24
        - used: false
          cidr: 10.20.107.0/24
        - used: false
          cidr: 10.20.108.0/24
        - used: false
          cidr: 10.20.109.0/24
        - used: false
          cidr: 10.20.110.0/24
        - used: false
          cidr: 10.20.111.0/24
        - used: false
          cidr: 10.20.112.0/24
        - used: false
          cidr: 10.20.113.0/24
        - used: false
          cidr: 10.20.114.0/24
        - used: false
          cidr: 10.20.115.0/24
        - used: false
          cidr: 10.20.116.0/24
        - used: false
          cidr: 10.20.117.0/24
        - used: false
          cidr: 10.20.118.0/24
        - used: false
          cidr: 10.20.119.0/24
        - used: false
          cidr: 10.20.120.0/24
        - used: false
          cidr: 10.20.121.0/24
        - used: false
          cidr: 10.20.122.0/24
        - used: false
          cidr: 10.20.123.0/24
        - used: false
          cidr: 10.20.124.0/24
        - used: false
          cidr: 10.20.125.0/24
        - used: false
          cidr: 10.20.126.0/24
        - used: false
          cidr: 10.20.127.0/24
        - used: false
          cidr: 10.20.128.0/24
        - used: false
          cidr: 10.20.129.0/24
        - used: false
          cidr: 10.20.130.0/24
        - used: false
          cidr: 10.20.131.0/24
        - used: false
          cidr: 10.20.132.0/24
        - used: false
          cidr: 10.20.133.0/24
        - used: false
          cidr: 10.20.134.0/24
        - used: false
          cidr: 10.20.135.0/24
        - used: false
          cidr: 10.20.136.0/24
        - used: false
          cidr: 10.20.137.0/24
        - used: false
          cidr: 10.20.138.0/24
        - used: false
          cidr: 10.20.139.0/24
        - used: false
          cidr: 10.20.140.0/24
        - used: false
          cidr: 10.20.141.0/24
        - used: false
          cidr: 10.20.142.0/24
        - used: false
          cidr: 10.20.143.0/24
        - used: false
          cidr: 10.20.144.0/24
        - used: false
          cidr: 10.20.145.0/24
        - used: false
          cidr: 10.20.146.0/24
        - used: false
          cidr: 10.20.147.0/24
        - used: false
          cidr: 10.20.148.0/24
        - used: false
          cidr: 10.20.149.0/24
        - used: false
          cidr: 10.20.150.0/24
        - used: false
          cidr: 10.20.151.0/24
        - used: false
          cidr: 10.20.152.0/24
        - used: false
          cidr: 10.20.153.0/24
        - used: false
          cidr: 10.20.154.0/24
        - used: false
          cidr: 10.20.155.0/24
        - used: false
          cidr: 10.20.156.0/24
        - used: false
          cidr: 10.20.157.0/24
        - used: false
          cidr: 10.20.158.0/24
        - used: false
          cidr: 10.20.159.0/24
        - used: false
          cidr: 10.20.160.0/24
        - used: false
          cidr: 10.20.161.0/24
        - used: false
          cidr: 10.20.162.0/24
        - used: false
          cidr: 10.20.163.0/24
        - used: false
          cidr: 10.20.164.0/24
        - used: false
          cidr: 10.20.165.0/24
        - used: false
          cidr: 10.20.166.0/24
        - used: false
          cidr: 10.20.167.0/24
        - used: false
          cidr: 10.20.168.0/24
        - used: false
          cidr: 10.20.169.0/24
        - used: false
          cidr: 10.20.170.0/24
        - used: false
          cidr: 10.20.171.0/24
        - used: false
          cidr: 10.20.172.0/24
        - used: false
          cidr: 10.20.173.0/24
        - used: false
          cidr: 10.20.174.0/24
        - used: false
          cidr: 10.20.175.0/24
        - used: false
          cidr: 10.20.176.0/24
        - used: false
          cidr: 10.20.177.0/24
        - used: false
          cidr: 10.20.178.0/24
        - used: false
          cidr: 10.20.179.0/24
        - used: false
          cidr: 10.20.180.0/24
        - used: false
          cidr: 10.20.181.0/24
        - used: false
          cidr: 10.20.182.0/24
        - used: false
          cidr: 10.20.183.0/24
        - used: false
          cidr: 10.20.184.0/24
        - used: false
          cidr: 10.20.185.0/24
        - used: false
          cidr: 10.20.186.0/24
        - used: false
          cidr: 10.20.187.0/24
        - used: false
          cidr: 10.20.188.0/24
        - used: false
          cidr: 10.20.189.0/24
        - used: false
          cidr: 10.20.190.0/24
        - used: false
          cidr: 10.20.191.0/24
        - used: false
          cidr: 10.20.192.0/24
        - used: false
          cidr: 10.20.193.0/24
        - used: false
          cidr: 10.20.194.0/24
        - used: false
          cidr: 10.20.195.0/24
        - used: false
          cidr: 10.20.196.0/24
        - used: false
          cidr: 10.20.197.0/24
        - used: false
          cidr: 10.20.198.0/24
        - used: false
          cidr: 10.20.199.0/24
        - used: false
          cidr: 10.20.200.0/24
        - used: false
          cidr: 10.20.201.0/24
        - used: false
          cidr: 10.20.202.0/24
        - used: false
          cidr: 10.20.203.0/24
        - used: false
          cidr: 10.20.204.0/24
        - used: false
          cidr: 10.20.205.0/24
        - used: false
          cidr: 10.20.206.0/24
        - used: false
          cidr: 10.20.207.0/24
        - used: false
          cidr: 10.20.208.0/24
        - used: false
          cidr: 10.20.209.0/24
        - used: false
          cidr: 10.20.210.0/24
        - used: false
          cidr: 10.20.211.0/24
        - used: false
          cidr: 10.20.212.0/24
        - used: false
          cidr: 10.20.213.0/24
        - used: false
          cidr: 10.20.214.0/24
        - used: false
          cidr: 10.20.215.0/24
        - used: false
          cidr: 10.20.216.0/24
        - used: false
          cidr: 10.20.217.0/24
        - used: false
          cidr: 10.20.218.0/24
        - used: false
          cidr: 10.20.219.0/24
        - used: false
          cidr: 10.20.220.0/24
        - used: false
          cidr: 10.20.221.0/24
        - used: false
          cidr: 10.20.222.0/24
        - used: false
          cidr: 10.20.223.0/24
        - used: false
          cidr: 10.20.224.0/24
        - used: false
          cidr: 10.20.225.0/24
        - used: false
          cidr: 10.20.226.0/24
        - used: false
          cidr: 10.20.227.0/24
        - used: false
          cidr: 10.20.228.0/24
        - used: false
          cidr: 10.20.229.0/24
        - used: false
          cidr: 10.20.230.0/24
        - used: false
          cidr: 10.20.231.0/24
        - used: false
          cidr: 10.20.232.0/24
        - used: false
          cidr: 10.20.233.0/24
        - used: false
          cidr: 10.20.234.0/24
        - used: false
          cidr: 10.20.235.0/24
        - used: false
          cidr: 10.20.236.0/24
        - used: false
          cidr: 10.20.237.0/24
        - used: false
          cidr: 10.20.238.0/24
        - used: false
          cidr: 10.20.239.0/24
        - used: false
          cidr: 10.20.240.0/24
        - used: false
          cidr: 10.20.241.0/24
        - used: false
          cidr: 10.20.242.0/24
        - used: false
          cidr: 10.20.243.0/24
        - used: false
          cidr: 10.20.244.0/24
        - used: false
          cidr: 10.20.245.0/24
        - used: false
          cidr: 10.20.246.0/24
        - used: false
          cidr: 10.20.247.0/24
        - used: false
          cidr: 10.20.248.0/24
        - used: false
          cidr: 10.20.249.0/24
        - used: false
          cidr: 10.20.250.0/24
        - used: false
          cidr: 10.20.251.0/24
        - used: false
          cidr: 10.20.252.0/24
        - used: false
          cidr: 10.20.253.0/24
        - used: false
          cidr: 10.20.254.0/24
        - used: false
          cidr: 10.20.255.0/24

